loom.platform=neoforge
fabric.loom.dontRemap=true

implementationVersion=2.1.5

versionMc=1.21.10
versionMcCompat=1.21.9
versionForge=21.10.12-beta
versionForgeCompat=21.10
versionForgifiedFabricLoader=2.5.55+0.17.2+1.21.1
versionFabricLoader=0.16.0

githubRepository=ThinkingStudios/ForgifiedFabricAPI
# This is the branch the release tag will be created from
publishBranch=1.21.10
