loom.platform=neoforge
fabric.loom.dontRemap=true

implementationVersion=2.2.5

versionMc=1.21.10
versionMcCompat=1.21.9
versionForge=21.10.63
versionForgeCompat=21.9
versionForgifiedFabricLoader=0.1.0+0.18.4+1.21.11
versionFabricLoader=0.18.4

githubRepository=ThinkingStudios/ForgifiedFabricAPI
# This is the branch the release tag will be created from
publishBranch=1.21.10
