loom.platform=neoforge
fabric.loom.dontRemap=true

implementationVersion=2.0.26

versionMc=1.21.8
versionForge=21.8.4-beta
versionForgeCompat=21.6
versionForgifiedFabricLoader=2.5.29+0.16.0+1.21
versionFabricLoader=0.16.0

githubRepository=ThinkingStudios/ForgifiedFabricAPI
# This is the branch the release tag will be created from
publishBranch=1.21.8
